version: '3.2'
 
services:
 
  main:
    image: martinfrancois/jenkins
    ports:
      - 8080:8080
      - 50000:50000
    secrets:
      - jenkins-user
      - jenkins-pass
    volumes:
      - type: volume
        source: jenkins_home
        target: /var/jenkins_home

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true

volumes:
  jenkins_home: