version: '3.2'
 
services:
 
  main:
    image: martinfrancois/jenkins
    ports:
      - 8080:8080
      - 50000:50000
    secrets:
      - jenkins-user
      - jenkins-pass
    volumes:
      - type: volume
        source: jenkins_home
        target: /var/jenkins_home
    command: rpl -i -w 'JAVA_ARGS="-Djava.awt.headless=true"' 'JAVA_ARGS="-Djava.awt.headless=true -Dhudson.model.DirectoryBrowserSupport.CSP=' /etc/default/jenkins
    # Needed to display JavaDoc correctly: https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true

volumes:
  jenkins_home: